spring:
  application:
    name: backend
  datasource:
    driverClassName: jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
    url: ENC(4kGfNJtsELjmDDnHJqmPdsAkD0CF6BDN2fp5FZ1FvTnxkFR8pBQ6buOqygDN1doJyBMUmr8HWQ9GB/yuahJlqnJwc/eOt019N9dzjzZkM2U7naEmc0/VURQAORCK/sNJjkJcwLx7kYE=)
    username: ENC(26ZMFzw7eKTUDEFDUwD2Sg==)
    password: ENC(jxh6IIJryl+zr6+jMZn4DgSyhYPxbQSh)
  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      algorithm: PBEWithMD5AndDES
      iv-generator-classname: org.jasypt.iv.NoIvGenerator
      password: 218905C7CD2C857E34E95E8FB59C0DDE3DCBFB97
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 842324597397-7rifslt6crb8im7vmnpmo7icef9q7spp.apps.googleusercontent.com
            client-secret: ENC(m+dlS+tCUXRU9W68SmWn3yh95Qp6P+NG5fRhDuR1RenSWqjcUrlqijMZghPPFNcY)
            scope: profile, email


jwt:
  secret:
    key: ENC(O0qNwaK41d4Wp22hne0XiRezVUCoclSxVVFUG6lhkEm3jPT7GqX5NOiLkOBDoGQPZDHeLtE8A2bXQZMkZgUKWCGdRx2xk+ylat+T8/ypMSYhdFwCNWD7FK6SdX2QNEtaRodFR/l3ibbiGFNmj0ZP66DRSY+TmMze1OCnNxbtCRgCo049qAcL1g==)
